version: "3.9"

networks:
  laravel_network:
services:
  nginx:
    build:
      context: .
      dockerfile: ./build/docker/nginx/nginx.dockerfile
    ports:
      - 8009:80
    volumes:
      - ./src:/var/www/html
      - ./build/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    env_file:
      - /src/.env
    depends_on:
      - php
      - mysql
    container_name: laravel_server
    networks:
      - laravel_network
  php:
    build:
      context: .
      dockerfile: ./build/docker/php/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    container_name: php_laravel
    networks:
      - laravel_network
  mysql:
    image: mysql:8.0.1
    restart: unless-stopped
    tty: true
    container_name: mysql_laravel
    env_file:
      - build/docker/mysql/.env
    ports:
      - 3306:3306
    networks:
      - laravel_network
    volumes:
      - /opt/mysql_data:/var/lib/mysql
